export const cards = [
  { type: '♠', typeName: 'spades', color: 'black', num: '2' },
  { type: '♠', typeName: 'spades', color: 'black', num: '3' },
  { type: '♠', typeName: 'spades', color: 'black', num: '4' },
  { type: '♠', typeName: 'spades', color: 'black', num: '5' },
  { type: '♠', typeName: 'spades', color: 'black', num: '6' },
  { type: '♠', typeName: 'spades', color: 'black', num: '7' },
  { type: '♠', typeName: 'spades', color: 'black', num: '8' },
  { type: '♠', typeName: 'spades', color: 'black', num: '9' },
  { type: '♠', typeName: 'spades', color: 'black', num: '10' },
  { type: '♠', typeName: 'spades', color: 'black', num: 'J' },
  { type: '♠', typeName: 'spades', color: 'black', num: 'Q' },
  { type: '♠', typeName: 'spades', color: 'black', num: 'K' },
  { type: '♠', typeName: 'spades', color: 'black', num: 'A' },

  { type: '♣', typeName: 'club', color: 'black', num: '2' },
  { type: '♣', typeName: 'club', color: 'black', num: '3' },
  { type: '♣', typeName: 'club', color: 'black', num: '4' },
  { type: '♣', typeName: 'club', color: 'black', num: '5' },
  { type: '♣', typeName: 'club', color: 'black', num: '6' },
  { type: '♣', typeName: 'club', color: 'black', num: '7' },
  { type: '♣', typeName: 'club', color: 'black', num: '8' },
  { type: '♣', typeName: 'club', color: 'black', num: '9' },
  { type: '♣', typeName: 'club', color: 'black', num: '10' },
  { type: '♣', typeName: 'club', color: 'black', num: 'J' },
  { type: '♣', typeName: 'club', color: 'black', num: 'Q' },
  { type: '♣', typeName: 'club', color: 'black', num: 'K' },
  { type: '♣', typeName: 'club', color: 'black', num: 'A' },

  { type: '♥', typeName: 'hearts', color: 'red', num: '2' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '3' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '4' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '5' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '6' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '7' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '8' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '9' },
  { type: '♥', typeName: 'hearts', color: 'red', num: '10' },
  { type: '♥', typeName: 'hearts', color: 'red', num: 'J' },
  { type: '♥', typeName: 'hearts', color: 'red', num: 'Q' },
  { type: '♥', typeName: 'hearts', color: 'red', num: 'K' },
  { type: '♥', typeName: 'hearts', color: 'red', num: 'A' },

  { type: '♦', typeName: 'diamond', color: 'red', num: '2' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '3' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '4' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '5' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '6' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '7' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '8' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '9' },
  { type: '♦', typeName: 'diamond', color: 'red', num: '10' },
  { type: '♦', typeName: 'diamond', color: 'red', num: 'J' },
  { type: '♦', typeName: 'diamond', color: 'red', num: 'Q' },
  { type: '♦', typeName: 'diamond', color: 'red', num: 'K' },
  { type: '♦', typeName: 'diamond', color: 'red', num: 'A' }
]
